### ISSUE TITLE
API-s not working in deafault docker deployment 

### ISSUE THREAD

**Issue by Haigutus** [opfab/operatorfabric-core#1072]
Hi

We are evaluating the operator fabric with the provided docker setup, but are not able to get any API working, all the commands get TypeError response

![version](https://user-images.githubusercontent.com/11408965/118633320-046df280-b7da-11eb-8419-bbe7e8040e74.png)

1.	Get users (no error in log)
2.	The card test script

1.

![user_api](https://user-images.githubusercontent.com/11408965/118633376-164f9580-b7da-11eb-8588-d600e4b189f6.png)

2.
2021-05-18 09:08:55.742 ERROR 10 --- [tp703232177-591] o.o.c.p.c.CustomExceptionHandler : Uncaught internal server exception org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `org.opfab.cards.publication.model.CardPublicationData` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.opfab.cards.publication.model.CardPublicationData` out of START_ARRAY token at [Source: (PushbackInputStream); line: 1, column: 1] at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:277) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:243) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:205) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:890) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:804) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1062) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4] at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.0-M1.jar!/:5.3.0-M1] at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4] at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226) ~[websocket-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:339) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:114) ~[spring-security-oauth2-resource-server-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:353) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:223) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:184) ~[spring-security-web-5.4.0-M1.jar!/:5.4.0-M1] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.0-M1.jar!/:2.4.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489) ~[jetty-servlet-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272) ~[jetty-server-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) ~[jetty-util-9.4.30.v20200611.jar!/:9.4.30.v20200611] at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na] Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.opfab.cards.publication.model.CardPublicationData` out of START_ARRAY token at [Source: (PushbackInputStream); line: 1, column: 1] at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:604) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:190) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482) ~[jackson-databind-2.11.1.jar!/:2.11.1] at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3487) ~[jackson-databind-2.11.1.jar!/:2.11.1] at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:266) ~[spring-web-5.3.0-M1.jar!/:5.3.0-M1] ... 100 common frames omitted

**Comment by AlexGuironnetRTE** [comment]
Hi Haigutus,

Thanks for your interest in OperatorFabric! Just a few quick questions to confirm what you are doing so I can try and reproduce the issue.

1) We you say you're running OpFab with the provided docker setup, you mean you pulled the latest commit from develop and ran ./config/docker/docker-compose.sh, is that correct? 

2) If you go to localhost:2002/ you are able to log in using one of the test credentials (for example operator1 / test) and see the UI?

3) I see you pasted a screenshot of the API documentation, are you running your api requests through it with the Try it out feature ? To be honest it's not something that we've been using, we only use it to document the API endpoints, expected inputs and responses. We usually call the APIs either using curl, Postman, the Karate tests or the OperatorFabric UI itself.
In any case it could be interesting to make the Try it out feature work, I'm going to see if fixing the base url and host does the trick and I'll get back to you (logged OC-1730).

4) What are you referring to when you say "the card test script" ? The karate tests ? Or push_card_loop.sh (this one has fallen out of use now that we have the Karate tests, so I logged a ticker to remove it as it doesn't work anymore).

In addition, you might be interested in checking out our [Getting Started guide](https://opfab.github.io/documentation/current/getting_started/) which can take you through the basic steps of using OperatorFabric (pushing configuration, then cards, etc.).

Have a good day !

**Comment by Haigutus** [comment]
1. Yes
2. Yes
3. Yes, I have not tested other options, but tested an option without any payload and the base url seems to be correct
4. Yes, as this is in the quick start guide

**Comment by Haigutus** [comment]
The steps were done as defined here in read-me
![image](https://user-images.githubusercontent.com/11408965/118650515-36d51b00-b7ed-11eb-9855-a5121396d7c6.png)

I will have a look to the Getting Started guide

**Comment by Haigutus** [comment]
Using the ./sendCard.sh card.json from Getting Started guide worked

**Comment by AlexGuironnetRTE** [comment]
Hello,

Thank you very much for your reply, glad that it worked! 

You are right, I've removed the script and updated the readme and documentation accordingly (#1080), thanks for pointing it out!

About testing the api using swagger-ui, the host is correct but the baseUrl shouldn't be /apis, it's different for each API (cards, businessconfig etc.) so I'm going to fix it (OC-1730) so the curl examples in the swagger-ui are correct but I'm afraid the Try it out feature still won't work as we would need to configure authentication.

Please let us know if you have any other issue, question or feedback!

**Comment by AlexGuironnetRTE** [comment]
The URL are fixed and we've added a warning that the "Try it out" button is not meant to work: https://github.com/opfab/operatorfabric-core/pull/1073

Is that ok with you if I close this issue ?
