### ISSUE TITLE
replace TSLint by ESLint

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1360]
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see 

  for more information.

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#getting-started---linting-your-typescript-codebase

https://eslint.org/docs/user-guide/migrating-to-7.0.0#drop-node-8

**Comment by vlo-rte** [comment]
Our version of Node.js  seems to be v14.15.5, so I propose to use ESLint 8.0.0 because it is the latest release and our version of node.js is supported by it.

https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0

**Comment by vlo-rte** [comment]
The warning about tslint has disappeared but I think this is not enough.
Impossible to use eslint : 

longaval@gm0winl136:~/Projects/operatorfabric-core/ui/main$ eslint
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'optionator'
Require stack:
- /usr/share/nodejs/eslint/lib/options.js
- /usr/share/nodejs/eslint/lib/cli.js
- /usr/share/nodejs/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/nodejs/eslint/lib/options.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/eslint/lib/options.js',
    '/usr/share/nodejs/eslint/lib/cli.js',
    '/usr/share/nodejs/eslint/bin/eslint.js'
  ]
}
