### ISSUE TITLE
Impossible to save settings for technical reasons - Issue when the user account ID contains a special character

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#2310]
Dear colleagues,

As discussed today during the OPCSTA's meeting, there is a user who encountered the following situation : 

- When changing the settings in the **_Notification Reception Configuration_** screen and clicking on the "**_Confirm settings_**" button
- The following message is displayed "**Impossible to save settings for technical reasons**"

![image](https://user-images.githubusercontent.com/79971866/147109308-d3fca6cc-16be-4539-a0cd-58639b4ed2d2.png)

Also, please find below the issue found in the console : 
![image](https://user-images.githubusercontent.com/79971866/147109380-687cc22b-f96c-4c72-8488-9dbefb93f7fa.png)

I remain available for any further question.

Kind regards,

Sascha

**Comment by vlo-rte** [comment]
I think the error is due to restriction in spring framework, maybe we should forbid special characters in login field (and id fields in general) ? 

2021-12-27 13:46:06.390  INFO 77049 --- [qtp176041373-19] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:9, serverValue:233}] to localhost:27017
2021-12-27 13:46:06.444  INFO 77049 --- [qtp176041373-21] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:10, serverValue:234}] to localhost:27017
2021-12-27 13:46:06.650  WARN 77049 --- [qtp176041373-57] org.eclipse.jetty.server.HttpChannel     : /users/opérator1/settings

org.springframework.security.web.firewall.RequestRejectedException: The requestURI was rejected because it can only contain printable ASCII characters.
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:436) ~[spring-security-web-5.6.1.jar!/:5.6.1]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196) ~[spring-security-web-5.6.1.jar!/:5.6.1]

**Comment by vlo-rte** [comment]
Even with Postman, GET http://localhost:2002/users/users/op%C3%A9rator1 generates the same exception in users service log, and 401 unauthorized response.

**Comment by vlo-rte** [comment]
Moreover, we have set a control in the UI to forbid special characters in login field, so I think a login with special character should not exist.

**Comment by vlo-rte** [comment]
For information, we have this issue : https://github.com/opfab/operatorfabric-core/issues/1318 which deals with quite the same problem.

**Comment by SaschaEschmann** [comment]
Thank you @vlo-rte for your analysis.

I confirm that on our side (within the OPCSTA project) we implemented a procedure to forbid the special characters in the login field during the account creation process (managed by our project partner).
