### ISSUE TITLE
Unable to launch the Demo docker.

### ISSUE THREAD

**Issue by ocou-aprico** [opfab/operatorfabric-core#38]
After cloning the project and building it, the compose up of the demo stack generates a lot of exceptions and the platform is not running correctly.
It looks that the registry and config containers are involved in a dead lock.

The registry failed to run because it is unable to connect the config container, but the config container is trying to connect the registry container.

From the registry container logs:
2019-01-21 16:06:14.146  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://config:8080
2019-01-21 16:06:14.161  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://config:8080. Will be trying the next url if available
2019-01-21 16:06:14.179 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:136) ~[spring-cloud-config-client-2.1.0.RC3.jar!/:2.1.0.RC3]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<

Form the config container logs:

2019-01-21 16:06:13.663  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-01-21 16:06:13.663  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-01-21 16:06:13.859 ERROR 1 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://registry:8080/eureka/}

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar!/:1.19.1]

Full log files are attached to this issue (note that I ran the demo twice, but with the same effect).
[config.log](https://github.com/opfab/operatorfabric-core/files/2780558/config.log)
[registry.log](https://github.com/opfab/operatorfabric-core/files/2780560/registry.log)

Best regards

Environment: Mac OS
Java 1.8 Gradle 4.7

Script

 514  git clone https://github.com/opfab/operatorfabric-core.git
  515  cd operatorfabric-core/
  516  bin/build_all.sh 
  517  bin/setup_dockerized_environment.sh 
  518  cd src/main/docker/demo/
  523  docker-compose up
  524  docker-compose up
  525  mkdir /tmp/opfab
  526  docker logs registry /tmp/opfab/registry.log
  527  docker logs registry >/tmp/opfab/registry.log

**Comment by davidbinderRTE** [comment]
I'll investigate this today but exceptions are surely to happen anyway as services have to wait for each others wich leads to multiple connection retries (though it should have succeed at some point which seems not to be the case in your log files).

We didn't had opportunities to test this on multiple docker versions what is yours ?

**Comment by ocou-aprico** [comment]
I observed that the registry container stopped to run according its configuration (fast fail=true, retries=10).
Probably the workaround is to increase the number of retries.
 When I restarted  it manually, exceptions about IO disappears but the client gateway continues to fail to work correctly (I will investigate this more later and come back to you with more details).


Docker version:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/46568404/51530166-a6fc4d80-1e3a-11e9-9483-6f66630ab0c0.png">

**Comment by davidbinderRTE** [comment]
I am reproducing the same behaviour on my side

> I observed that the registry container stopped to run according its configuration (fast fail=true, retries=10).
> Probably the workaround is to increase the number of retries.

After a bit of run and tries, I came to the same conclusion.
